dargmuesli/nuxt-cookie-control

- package.json
- src/runtime/components/CookieControl.vue
- src/runtime/types.ts
> fix: display banner with no colors

- README.md
- src/runtime/locale/ko.ts
> feat(ko): Add Korean cookie

- src/runtime/locale/az.ts
Updated "bannerDescription" translation for Azerbaijani language
> feat: Updated bannerDescription translation for Azerbaijani language

- README.md
- src/runtime/locale/cs.ts
- src/runtime/locale/sk.ts
> feat(locale): add Czech and Slovak locales

- playground/nuxt.config.ts
- src/module.ts
- src/runtime/types.ts
> fix(module): correct locale text input

- README.md
- playground/app.vue
- playground/nuxt.config.ts
- src/runtime/components/CookieControl.vue
- src/runtime/styles.css
- src/runtime/types.ts
> feat: wcag compliance

- README.md
- src/runtime/components/CookieControl.vue
- src/runtime/methods.ts
- src/runtime/plugin.ts
- src/runtime/types.ts
> feat: show banner again once cookies are added or removed

- playground/nuxt.config.ts
- src/runtime/components/CookieControl.vue
- src/runtime/types.ts
> feat(cookie): allow to add links

- package.json
- pnpm-lock.yaml
> chore(deps): update dependency nuxt and @nuxt/kit to v3.2.3

- .github/workflows/ci.yml
- README.md
- src/runtime/locale/sv.ts
> feat(locale): add Swedish locale

- src/runtime/locale/fi.ts
- src/runtime/types.ts
feat(lang): add Finnish locale (fi)
> feat(lang): add Finnish locale (fi)

- README.md
- src/runtime/locale/index.ts
- src/runtime/locale/pl.ts
- src/runtime/types.ts
This PR add new language to the list -> Polish (PL)
> feat(locale): add PL - Polish translation

- README.md
- src/runtime/locale/index.ts
- src/runtime/locale/oc.ts
- src/runtime/types.ts
I hope it's correct to contribuite this way!
> feat(i18n): add Occitan language

- src/runtime/components/CookieControl.vue
Added the defineExpose function to make the methods (accept, acceptPartial, decline) available in parent components through refs.
> feat(method): add define Expose - make methods available to parent component

- src/runtime/locale/hu.ts
I'm Hungarian and that's right
> fix(locale): correct hungarian translations

- README.md
- src/runtime/locale/ca.ts
- src/runtime/locale/index.ts
- src/runtime/types.ts
This PR add new language to the list -> Catalan (CA)
> feat(locale): add CA - Catalan translation

- .github/workflows/ci.yml
- .github/workflows/release-schedule.yml
- package.json
- pnpm-lock.yaml
> ci: pin node 20.5.1

- .github/workflows/ci.yml
- pnpm-lock.yaml
Upgrading dependencies, unblocking the usage of Node latest.
> chore(deps): upgrade

- .vscode/extensions.json
- .vscode/settings.json
- README.md
- add vscode ide configuration
- add missing slot wrapper to README
> chore: housekeeping

- .github/workflows/ci.yml
- .github/workflows/release-schedule.yml
- update dargmuesli/github-actions action to v1.1.5
> chore(deps): update dargmuesli/github-actions action to v1.1.5

- .github/workflows/ci.yml
- .github/workflows/release-schedule.yml
- .npmrc
- package.json
- pnpm-lock.yaml
- src/runtime/methods.ts
> chore(npm): disable shameful hoisting

- .releaserc
- CHANGELOG.md
- README.md
- package.json
- pnpm-lock.yaml
- src/runtime/components/CookieControl.vue
- src/runtime/styles.css
- replaces the `section` in `CookieControl` with an `aside`
- makes use of `h2`s instead of `h3`s
> feat: beta

- package.json
- pnpm-lock.yaml
> chore: package

- README.md
- src/runtime/locale/id.ts
- src/runtime/locale/index.ts
- src/runtime/types.ts
This PR add new language to the list -> Indonesian (ID)
> feat(locale): add ID - Bahasa(Indonesian) translation

- .nuxtrc
Bundler resolution should be the default now.
> fix(nuxt): remove config file

- README.md
- src/runtime/locale/be.ts
- src/runtime/locale/index.ts
- src/runtime/types.ts
> feat: add BE locale

- README.md
- src/runtime/components/CookieControl.vue
- src/runtime/plugin.ts
- src/runtime/types.ts
I implemented a small feature which let’s the website owner choose some recommended cookies. These are only preselected on the first modal open when “isConsentGiven” is undefined. To comply with GDPR no actual cookies are being set - only the checkboxes are preselected so when users click on “accept selected” the recommended cookies will get enabled.
> feat: add initial recommended state management

- CONTRIBUTING.md
- README.md
> docs: add contribute new locale instruction

- playground/nuxt.config.ts
- src/runtime/components/CookieControl.vue
adds functionality to specify a cookie link to a local page inside your nuxt app or to an external full link.
"Resolves #197"
> feat(links)!: differentiate external from internal links

- .eslintrc
- package.json
- playground/package.json
- src/tsconfig.json
Update to the newly introduced type preparation.
> chore(nuxt-module-build): update prepare script

- README.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
> fix: schedule release

- README.md
- src/runtime/locale/index.ts
- src/runtime/locale/sl.ts
- src/runtime/types.ts
Added Slovenian language to the locales. The added language follows the [ISO_639](https://en.wikipedia.org/wiki/ISO_639) standard
> feat: added slovenian language

- .github/workflows/ci.yml
- playground/nuxt.config.ts
- pnpm-workspace.yaml
> chore(playground): set nuxt compatiblity version to v4

- src/runtime/components/CookieControl.vue
Buttons should have a type. This PR sets these.
> fix(components): set button types

- .renovaterc
- package.json
- pnpm-lock.yaml
Newer versions of typescript are compatible now.
> chore(deps): unpin typescript

- .github/workflows/ci.yml
- .renovaterc
- package.json
- pnpm-lock.yaml
Add a build step to the CI pipeline that runs before actually building for release.
> ci: add build

- src/types.ts
Resolve a previous limitation that has been fixed upstream.
> chore(types): reenable i18n import of locale texts

- README.md
- playground/app.vue
- src/runtime/components/CookieControl.vue
- src/runtime/components/CookieIframe.vue
Resolves https://github.com/dargmuesli/nuxt-cookie-control/issues/246
> feat(iframe): add slot

- .github/workflows/ci.yml
- .github/workflows/release-schedule.yml
- package.json
- pnpm-lock.yaml
Resolves various package manager issues, e.g. https://github.com/nodejs/corepack/issues/612.
> chore(deps): upgrade pnpm to v10

- src/runtime/components/CookieControl.vue
> refactor(vue): use reactive props destructure

- src/runtime/components/CookieControl.vue
> refactor: minor cleanup

- src/runtime/locale/tr.ts
> fix(i18n): update turkish
